import type { Body, OrbitDataKind, PlanetSystem } from "@/types";

const LAST_SYNCED_AT = "2026-04-14T00:00:00.000Z";
const PLANET_PHYSICAL_SOURCE = "JPL SSD Planetary Physical Parameters";
const SATELLITE_PHYSICAL_SOURCE = "JPL SSD Planetary Satellite Physical Parameters";
const ORBIT_REFERENCE_SOURCE =
  "Reference orbit geometry generated from cataloged mean orbital values for education. Not a realtime ephemeris.";
const SHAPE_REFERENCE_SOURCE =
  "Current local bundle uses a scientific approximation. Official NASA/PDS shape sources are referenced for future ingestion.";

const SOURCE_URLS = {
  horizons: "https://ssd-api.jpl.nasa.gov/doc/horizons.html",
  satelliteOrbits: "https://ssd.jpl.nasa.gov/sats/orbits.html",
  satellitePhysical: "https://ssd.jpl.nasa.gov/sats/phys_par/",
  satelliteDiscovery: "https://ssd.jpl.nasa.gov/sats/discovery.html",
  planetPhysical: "https://ssd.jpl.nasa.gov/planets/phys_par.html",
  earthModel: "https://science.nasa.gov/resource/earth-3d-model/",
  moonModel: "https://science.nasa.gov/moon-3d/",
  marsModel: "https://science.nasa.gov/resource/planet-mars-3d-model/",
  jupiterModel: "https://science.nasa.gov/resource/jupiter-3d-model/",
  saturnModel: "https://science.nasa.gov/resource/saturn-3d-model/",
  phobosModel: "https://science.nasa.gov/resource/phobos-mars-moon-3d-model/",
  europaModel: "https://science.nasa.gov/resource/europa-3d-model/",
  enceladusModel: "https://science.nasa.gov/resource/enceladus-3d-model/",
  titanModel: "https://science.nasa.gov/resource/titan-3d-model/",
  plutoModel: "https://science.nasa.gov/resource/pluto-3d-model/",
  charonModel: "https://science.nasa.gov/resource/charon-3d-model/",
} as const;

const systemNameMap = {
  "system-inner": { english: "Inner Solar System", chinese: "内太阳系" },
  "system-earth": { english: "Earth System", chinese: "地月系统" },
  "system-mars": { english: "Mars System", chinese: "火星系统" },
  "system-jupiter": { english: "Jupiter System", chinese: "木星系统" },
  "system-saturn": { english: "Saturn System", chinese: "土星系统" },
  "system-uranus": { english: "Uranus System", chinese: "天王星系统" },
  "system-neptune": { english: "Neptune System", chinese: "海王星系统" },
  "system-pluto": { english: "Pluto System", chinese: "冥王星系统" },
} as const;

const featuredContent: Record<
  string,
  Pick<Body, "descriptionOneLine" | "descriptionShort" | "descriptionMedium" | "descriptionLong">
> = {
  sun: {
    descriptionOneLine: "太阳是太阳系的主恒星，支配着所有行星与卫星的能量和引力环境。",
    descriptionShort:
      "太阳约占太阳系总质量的 99.8%，其辐射、磁场和引力共同塑造了太阳风、行星气候以及整个太阳系的动力学边界。",
    descriptionMedium:
      "太阳是一颗 G 型主序星，也是太阳系唯一的恒星。对观测网站而言，太阳既是光照来源，也是所有轨道的引力核心。无论是行星的公转周期、卫星系统的稳定区，还是彗星与小天体的长期演化，都以太阳为中心展开。MVP 阶段的 3D 太阳将使用程序化发光球体与分层日冕表现，但页面会明确标注这是视觉近似，不是太阳表面的物理模拟。",
    descriptionLong:
      "太阳的内部由核心、辐射区和对流区组成，外部则包括光球、色球和日冕。其能量来自核心中的核聚变，氢通过质子-质子链反应转化为氦并释放巨大能量。太阳的活动周期、黑子、耀斑和日冕物质抛射会影响整个日球层，并与地球空间天气直接相关。在本项目中，太阳不仅是视觉主角，也是用户理解太阳系层级结构的切入点。",
  },
  earth: {
    descriptionOneLine: "地球是目前已知唯一拥有稳定表面液态水和生命的行星。",
    descriptionShort:
      "地球位于太阳宜居带内侧附近，具有复杂的大气、水圈、岩石圈和磁场系统，也是理解行星演化与卫星形成的关键参照。",
    descriptionMedium:
      "地球在本项目中既是一颗行星，也是一套完整系统的入口，因为月球对地球的潮汐、自转稳定性和长期演化具有深远影响。页面会同时展示真实物理参数、参考轨道和科学近似 3D 模型，并清楚区分“当前本地模型表现”和“可追溯的真实数据来源”。",
    descriptionLong:
      "地球的平均半径约为 6371 公里，质量约 5.97×10^24 千克，自转周期接近 24 小时，绕日公转周期约为 365.256 天。地球并非孤立存在，而是与月球构成一个强耦合的双体系统。理解地球系统不仅要看地球本身，还要把地月角动量交换、潮汐锁定趋势和卫星起源放到一起看。",
  },
  moon: {
    descriptionOneLine: "月球是地球唯一的天然卫星，也是人类研究最深入的天体之一。",
    descriptionShort:
      "月球控制着显著的海洋潮汐效应，并作为近距离岩质卫星，为撞击史、火山史与潮汐演化研究提供了高价值样本。",
    descriptionMedium:
      "月球在视觉上适合使用高质量球形近似与灰度地貌纹理，但本项目会继续标注其当前模型级别。轨道方面，MVP 使用参考采样轨道解释地月关系；更高精度版本可接入 Horizons 或 SPICE 做离线预计算。",
    descriptionLong:
      "月球平均半径约 1737.4 公里，自转与公转周期几乎相等，因此长期以同一面朝向地球。关于月球起源，目前主流假说为巨撞击起源。月球的背面地壳更厚、正面玄武岩平原更多，这一不对称结构是理解其热演化与撞击历史的重要线索。",
  },
  mars: {
    descriptionOneLine: "火星是一颗寒冷干燥的岩质行星，也是最重要的类地行星对照样本之一。",
    descriptionShort:
      "火星拥有稀薄大气、极冠、古河谷与大型火山构造，同时配有两颗体积很小但动力学意义很强的天然卫星。",
    descriptionMedium:
      "火星系统页面会同时强调主星与火卫一、火卫二的尺寸反差。MVP 里火星本体采用科学近似球形模型，火卫一和火卫二则保留参考轨道、尺寸和来源标签，帮助用户区分“真实物理参数”和“当前模型表现”。",
    descriptionLong:
      "火星平均半径约 3389.5 公里，一天长度约 24.6 小时，季节变化、沙尘活动和极区挥发过程使其成为比较行星学的关键对象。与地球相比，火星质量更小、磁场更弱、大气更稀薄，但依然保留了丰富的地貌证据，用于研究早期类地行星环境演化。",
  },
  jupiter: {
    descriptionOneLine: "木星是太阳系最大的行星，也是拥有庞大卫星家族的行星系统核心。",
    descriptionShort:
      "木星的强大引力塑造了复杂的卫星层级，从伽利略四大卫星到众多远距不规则卫星，共同构成研究共振与捕获起源的最佳实验场。",
    descriptionMedium:
      "木星系统页会把伽利略卫星放在视觉和学习双重中心，同时保留长尾卫星目录、筛选和来源标签。MVP 的轨道线是参考轨道采样，重点解释系统结构而不是伪装成实时高精星历。",
    descriptionLong:
      "木星质量约为地球的 318 倍，自转极快，内部存在深厚的大气层、强磁场和巨大的辐射环境。木卫一、欧罗巴、盖尼米得和卡利斯托在组成、热演化和潮汐加热方面差异显著，是理解冰卫星海洋、火山活动和轨道共振的核心样本。",
  },
  saturn: {
    descriptionOneLine: "土星是环系统最醒目的行星，同时也是已知卫星数量极其庞大的系统中心。",
    descriptionShort:
      "土星系统把环、内侧小卫星、冰质中型卫星、泰坦与远距不规则卫星串联在一起，是观察系统复杂度的典型案例。",
    descriptionMedium:
      "在 MVP 中，土星将用程序化环面与层级光照营造电影感，同时把泰坦、恩克拉多斯等重点对象提升到可进入详情页的学习节点。页面会明确说明哪些轨道与模型仍是参考级近似。",
    descriptionLong:
      "土星平均半径约 58232 公里，密度低于水，最著名的特征是由冰粒与碎屑组成的行星环。其卫星系统内部差异巨大：泰坦拥有浓厚大气，恩克拉多斯具有喷流与地下海洋迹象，而大量远距不规则卫星则记录了系统外层的捕获历史。",
  },
  europa: {
    descriptionOneLine: "欧罗巴是木星系统最受关注的冰卫星之一，因地下海洋潜力而备受重视。",
    descriptionShort:
      "欧罗巴的冰壳、潮汐加热和可能存在的全球液态海洋，使它成为太阳系潜在宜居环境研究的关键对象。",
    descriptionMedium:
      "MVP 详情页会展示欧罗巴的参考轨道、参数卡和模型等级说明。虽然当前本地模型仍为科学近似球体，但来源区会明确挂出官方 3D 资源与物理数据入口。",
    descriptionLong:
      "欧罗巴表面年轻、撞击坑较少，布满裂缝与带状结构。其内部可能由冰壳、全球海洋和岩质核心组成。由于受木星和共振伙伴的潮汐作用持续加热，欧罗巴成为太阳系海洋世界研究的头号目标之一。",
  },
  ganymede: {
    descriptionOneLine: "盖尼米得是太阳系最大的卫星，甚至比水星还大。",
    descriptionShort:
      "盖尼米得拥有复杂的冰岩结构和自身磁场，是木星系统中最具行星尺度感的卫星。",
    descriptionMedium:
      "盖尼米得的页面重点强调其尺寸、磁场特殊性和与欧罗巴、卡利斯托的差异。3D 模型在 MVP 中仍是科学近似，但参数和来源字段会保持真实可追溯。",
    descriptionLong:
      "盖尼米得平均半径约 2634 公里，是唯一已知具有内禀磁场的卫星。其表面同时保留古老高陨石坑地形与较年轻的沟槽地貌，说明内部热史与构造重塑过程非常复杂。",
  },
  enceladus: {
    descriptionOneLine: "恩克拉多斯是一颗体积不大却极具科学价值的冰卫星。",
    descriptionShort:
      "卡西尼任务发现其南极喷流和地下海洋迹象，使它成为寻找太阳系海洋生命线索的重要候选体。",
    descriptionMedium:
      "本项目会把恩克拉多斯作为土星系统中的重点学习对象，突出喷流、反照率和海洋世界属性，同时保留模型等级与形状来源说明。",
    descriptionLong:
      "恩克拉多斯平均半径约 252 公里，却表现出远超体积预期的内部活动。南极条纹地形喷出的水汽与冰粒持续补给土星 E 环，也让它成为理解潮汐加热和地下海洋可居住性的关键样本。",
  },
  titan: {
    descriptionOneLine: "泰坦是太阳系唯一拥有浓厚大气层的大型卫星。",
    descriptionShort:
      "它的大气、液态烃循环和复杂有机化学，使泰坦成为理解类地表面过程在极寒环境中如何发生的独特对象。",
    descriptionMedium:
      "泰坦在 MVP 中将重点展示其尺寸、轨道、模型等级与来源说明。虽然本地模型仍是近似球体，但内容层会把泰坦的气候与表面循环讲清楚。",
    descriptionLong:
      "泰坦平均半径约 2574.7 公里，大气以氮为主，表面存在甲烷和乙烷湖海。它既像一颗被冰冷改写的类地世界，也是一座天然的有机化学实验室，对行星气候和前生物化学研究都极具价值。",
  },
  pluto: {
    descriptionOneLine: "冥王星是矮行星系统的代表对象，其与冥卫一构成了极具特色的双体体系。",
    descriptionShort:
      "冥王星拥有氮冰、甲烷冰与年轻地貌共存的表面，而冥卫一相对巨大的质量使整个系统的动力学特征十分突出。",
    descriptionMedium:
      "冥王星系统页会把冥王星、冥卫一以及其他小卫星放在同一学习视图中，强调“矮行星系统成员”这一类别，而不是把它简单当作普通行星附属系统。",
    descriptionLong:
      "新视野号显示冥王星远比预想中活跃，拥有心形平原、冰川流动迹象和复杂的挥发物循环。冥王星与冥卫一围绕系统质心共同运动，提供了理解外太阳系小型系统结构的优秀案例。",
  },
  charon: {
    descriptionOneLine: "冥卫一是冥王星最大的卫星，大到足以让系统质心位于主天体外部。",
    descriptionShort:
      "冥卫一与冥王星的质量比极高，使它们更像一对双体系统而非典型的主星-卫星关系。",
    descriptionMedium:
      "在本项目中，冥卫一会被放在系统结构解读的中心位置。页面不仅展示参数卡，也会明确说明当前 3D 模型仍为科学近似。",
    descriptionLong:
      "冥卫一表面主要由水冰组成，与冥王星在颜色和挥发物分布上存在显著差异。由于潮汐锁定，冥王星与冥卫一始终以同一面相对，是太阳系中非常特殊的一组双体对象。",
  },
};

type BodyInput = Omit<
  Body,
  | "descriptionOneLine"
  | "descriptionShort"
  | "descriptionMedium"
  | "descriptionLong"
  | "aliases"
  | "lastSyncedAt"
  | "sources"
  | "provisionalDesignation"
  | "iauNumber"
  | "discoveryYear"
  | "orbitAvailability"
>;

function slugify(value: string) {
  return value
    .toLowerCase()
    .replace(/[()]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

function createTemplateContent(name: string, chineseName: string, parentLabel?: string) {
  const parentText = parentLabel ? `属于${parentLabel}` : "已纳入当前目录";

  return {
    descriptionOneLine: `${chineseName}（${name}）是${parentText}的目录级已知天体。`,
    descriptionShort: `${chineseName}（${name}）已纳入当前站点的结构化目录。MVP 阶段优先保证其命名、系统归属、来源标签与参考轨道链路正确，并在模型层明确标记为科学近似或占位近似。`,
    descriptionMedium: `${chineseName}（${name}）当前详情页将提供系统归属、基础参数卡、来源信息、轨道类型标记与模型等级说明。若缺少高精形状资源，本项目会保留真实目录数据并使用近似几何进行展示，而不会把近似模型伪装成真实扫描结果。`,
  };
}

function buildBody(input: BodyInput, aliases: string[], shapeSources: string[], contentSources?: string[]): Body {
  const featured = featuredContent[input.slug];
  const fallback = createTemplateContent(input.englishName, input.chineseName, input.systemId ? systemNameMap[input.systemId as keyof typeof systemNameMap]?.chinese : undefined);

  return {
    ...input,
    aliases,
    descriptionOneLine: featured?.descriptionOneLine ?? fallback.descriptionOneLine,
    descriptionShort: featured?.descriptionShort ?? fallback.descriptionShort,
    descriptionMedium: featured?.descriptionMedium ?? fallback.descriptionMedium,
    descriptionLong: featured?.descriptionLong,
    lastSyncedAt: LAST_SYNCED_AT,
    provisionalDesignation: null,
    iauNumber: null,
    discoveryYear: null,
    orbitAvailability: input.horizonsId ? "reference_only" : "unresolved",
    sources: {
      orbit: [SOURCE_URLS.satelliteOrbits, SOURCE_URLS.horizons],
      physical: [
        input.bodyType === "natural_satellite" ? SOURCE_URLS.satellitePhysical : SOURCE_URLS.planetPhysical,
      ],
      shape: shapeSources,
      content: contentSources ?? ["https://science.nasa.gov/solar-system/"],
    },
  };
}

function makePlanet({
  id,
  officialName,
  chineseName,
  englishName,
  radiusKm,
  massKg,
  density,
  gravity,
  escapeVelocity,
  albedo,
  rotationPeriodHours,
  orbitalPeriodDays,
  semiMajorAxisKm,
  eccentricity,
  inclinationDeg,
  horizonsId,
  naifId,
  systemId = "system-inner",
  featured = false,
}: {
  id: string;
  officialName: string;
  chineseName: string;
  englishName: string;
  radiusKm?: number | null;
  massKg?: number | null;
  density?: number | null;
  gravity?: number | null;
  escapeVelocity?: number | null;
  albedo?: number | null;
  rotationPeriodHours?: number | null;
  orbitalPeriodDays?: number | null;
  semiMajorAxisKm?: number | null;
  eccentricity?: number | null;
  inclinationDeg?: number | null;
  horizonsId: string | null;
  naifId: string | null;
  systemId?: string;
  featured?: boolean;
}) {
  return buildBody(
    {
      id,
      slug: slugify(englishName),
      officialName,
      chineseName,
      englishName,
      bodyType: id === "pluto" ? "dwarf_planet" : "planet",
      parentId: "sun",
      systemId,
      orbitSource: ORBIT_REFERENCE_SOURCE,
      physicalSource: PLANET_PHYSICAL_SOURCE,
      shapeSource: SHAPE_REFERENCE_SOURCE,
      modelGrade: "B",
      radiusKm,
      meanRadiusKm: radiusKm,
      massKg: massKg ?? null,
      density: density ?? null,
      gravity: gravity ?? null,
      escapeVelocity: escapeVelocity ?? null,
      albedo: albedo ?? null,
      rotationPeriodHours: rotationPeriodHours ?? null,
      orbitalPeriodDays: orbitalPeriodDays ?? null,
      semiMajorAxisKm: semiMajorAxisKm ?? null,
      eccentricity: eccentricity ?? null,
      inclinationDeg: inclinationDeg ?? null,
      discoveryText: null,
      texturePath: null,
      modelPath: null,
      thumbnailPath: null,
      hasHighFidelityShape: false,
      featured,
      horizonsId,
      naifId,
      orbitDataKind: "mean_elements_reference",
      catalogStatus: "confirmed",
    },
    [officialName],
    [
      SOURCE_URLS.earthModel,
      SOURCE_URLS.marsModel,
      SOURCE_URLS.jupiterModel,
      SOURCE_URLS.saturnModel,
      SOURCE_URLS.plutoModel,
    ],
  );
}

function makeMoon({
  id,
  englishName,
  chineseName,
  officialName = englishName,
  parentId,
  systemId,
  discoveryText = null,
  meanRadiusKm = null,
  massKg = null,
  density = null,
  gravity = null,
  escapeVelocity = null,
  albedo = null,
  rotationPeriodHours = null,
  orbitalPeriodDays = null,
  semiMajorAxisKm = null,
  eccentricity = null,
  inclinationDeg = null,
  triAxialRadiiKm = null,
  featured = false,
  horizonsId = null,
  naifId = null,
  aliases = [],
  shapeUrls = [],
  catalogStatus = "confirmed",
  orbitDataKind = "mean_elements_reference",
}: {
  id: string;
  englishName: string;
  chineseName: string;
  officialName?: string;
  parentId: string;
  systemId: Body["systemId"];
  discoveryText?: string | null;
  meanRadiusKm?: number | null;
  massKg?: number | null;
  density?: number | null;
  gravity?: number | null;
  escapeVelocity?: number | null;
  albedo?: number | null;
  rotationPeriodHours?: number | null;
  orbitalPeriodDays?: number | null;
  semiMajorAxisKm?: number | null;
  eccentricity?: number | null;
  inclinationDeg?: number | null;
  triAxialRadiiKm?: [number, number, number] | null;
  featured?: boolean;
  horizonsId?: string | null;
  naifId?: string | null;
  aliases?: string[];
  shapeUrls?: string[];
  catalogStatus?: Body["catalogStatus"];
  orbitDataKind?: OrbitDataKind;
}) {
  return buildBody(
    {
      id,
      slug: slugify(englishName),
      officialName,
      chineseName,
      englishName,
      bodyType: "natural_satellite",
      parentId,
      systemId,
      orbitSource: ORBIT_REFERENCE_SOURCE,
      physicalSource: SATELLITE_PHYSICAL_SOURCE,
      shapeSource: SHAPE_REFERENCE_SOURCE,
      modelGrade: "B",
      radiusKm: meanRadiusKm,
      meanRadiusKm,
      triAxialRadiiKm,
      massKg,
      density,
      gravity,
      escapeVelocity,
      albedo,
      rotationPeriodHours,
      orbitalPeriodDays,
      semiMajorAxisKm,
      eccentricity,
      inclinationDeg,
      discoveryText,
      texturePath: null,
      modelPath: null,
      thumbnailPath: null,
      hasHighFidelityShape: false,
      featured,
      horizonsId,
      naifId,
      orbitDataKind,
      catalogStatus,
    },
    [officialName, ...aliases],
    shapeUrls,
  );
}

export function buildSeedBodies(): Body[] {
  const bodies: Body[] = [
    buildBody(
      {
        id: "sun",
        slug: "sun",
        officialName: "Sun",
        chineseName: "太阳",
        englishName: "Sun",
        bodyType: "star",
        parentId: null,
        systemId: null,
        orbitSource: "Central star; no orbit sample in this site.",
        physicalSource: PLANET_PHYSICAL_SOURCE,
        shapeSource: SHAPE_REFERENCE_SOURCE,
        modelGrade: "B",
        radiusKm: 695700,
        meanRadiusKm: 695700,
        massKg: 1.9885e30,
        density: 1.408,
        gravity: 274,
        escapeVelocity: 617.7,
        albedo: null,
        rotationPeriodHours: 609.12,
        orbitalPeriodDays: null,
        semiMajorAxisKm: null,
        eccentricity: null,
        inclinationDeg: null,
        discoveryText: null,
        texturePath: null,
        modelPath: null,
        thumbnailPath: null,
        hasHighFidelityShape: false,
        featured: true,
        horizonsId: "10",
        naifId: "10",
        orbitDataKind: "manual_reference",
        catalogStatus: "confirmed",
      },
      ["Sol"],
      [SOURCE_URLS.horizons],
      ["https://science.nasa.gov/sun/"],
    ),
    makePlanet({
      id: "mercury",
      officialName: "Mercury",
      chineseName: "水星",
      englishName: "Mercury",
      radiusKm: 2439.7,
      massKg: 3.3011e23,
      density: 5.43,
      gravity: 3.7,
      escapeVelocity: 4.25,
      albedo: 0.142,
      rotationPeriodHours: 1407.5,
      orbitalPeriodDays: 87.969,
      semiMajorAxisKm: 57909050,
      eccentricity: 0.2056,
      inclinationDeg: 7.005,
      horizonsId: "199",
      naifId: "199",
    }),
    makePlanet({
      id: "venus",
      officialName: "Venus",
      chineseName: "金星",
      englishName: "Venus",
      radiusKm: 6051.8,
      massKg: 4.8675e24,
      density: 5.24,
      gravity: 8.87,
      escapeVelocity: 10.36,
      albedo: 0.689,
      rotationPeriodHours: -5832.5,
      orbitalPeriodDays: 224.701,
      semiMajorAxisKm: 108208000,
      eccentricity: 0.0068,
      inclinationDeg: 3.394,
      horizonsId: "299",
      naifId: "299",
    }),
    makePlanet({
      id: "earth",
      officialName: "Earth",
      chineseName: "地球",
      englishName: "Earth",
      radiusKm: 6371,
      massKg: 5.97219e24,
      density: 5.51,
      gravity: 9.81,
      escapeVelocity: 11.186,
      albedo: 0.306,
      rotationPeriodHours: 23.934,
      orbitalPeriodDays: 365.256,
      semiMajorAxisKm: 149598023,
      eccentricity: 0.0167,
      inclinationDeg: 0,
      horizonsId: "399",
      naifId: "399",
      systemId: "system-earth",
      featured: true,
    }),
    makePlanet({
      id: "mars",
      officialName: "Mars",
      chineseName: "火星",
      englishName: "Mars",
      radiusKm: 3389.5,
      massKg: 6.4171e23,
      density: 3.93,
      gravity: 3.71,
      escapeVelocity: 5.03,
      albedo: 0.17,
      rotationPeriodHours: 24.623,
      orbitalPeriodDays: 686.98,
      semiMajorAxisKm: 227939200,
      eccentricity: 0.0934,
      inclinationDeg: 1.85,
      horizonsId: "499",
      naifId: "499",
      systemId: "system-mars",
      featured: true,
    }),
    makePlanet({
      id: "jupiter",
      officialName: "Jupiter",
      chineseName: "木星",
      englishName: "Jupiter",
      radiusKm: 69911,
      massKg: 1.89813e27,
      density: 1.33,
      gravity: 24.79,
      escapeVelocity: 59.5,
      albedo: 0.538,
      rotationPeriodHours: 9.925,
      orbitalPeriodDays: 4332.59,
      semiMajorAxisKm: 778570000,
      eccentricity: 0.0489,
      inclinationDeg: 1.304,
      horizonsId: "599",
      naifId: "599",
      systemId: "system-jupiter",
      featured: true,
    }),
    makePlanet({
      id: "saturn",
      officialName: "Saturn",
      chineseName: "土星",
      englishName: "Saturn",
      radiusKm: 58232,
      massKg: 5.6834e26,
      density: 0.687,
      gravity: 10.44,
      escapeVelocity: 35.5,
      albedo: 0.499,
      rotationPeriodHours: 10.7,
      orbitalPeriodDays: 10759.22,
      semiMajorAxisKm: 1433530000,
      eccentricity: 0.0565,
      inclinationDeg: 2.485,
      horizonsId: "699",
      naifId: "699",
      systemId: "system-saturn",
      featured: true,
    }),
    makePlanet({
      id: "uranus",
      officialName: "Uranus",
      chineseName: "天王星",
      englishName: "Uranus",
      radiusKm: 25362,
      massKg: 8.681e25,
      density: 1.27,
      gravity: 8.69,
      escapeVelocity: 21.3,
      albedo: 0.488,
      rotationPeriodHours: -17.24,
      orbitalPeriodDays: 30688.5,
      semiMajorAxisKm: 2872460000,
      eccentricity: 0.046,
      inclinationDeg: 0.772,
      horizonsId: "799",
      naifId: "799",
      systemId: "system-uranus",
      featured: true,
    }),
    makePlanet({
      id: "neptune",
      officialName: "Neptune",
      chineseName: "海王星",
      englishName: "Neptune",
      radiusKm: 24622,
      massKg: 1.02413e26,
      density: 1.64,
      gravity: 11.15,
      escapeVelocity: 23.5,
      albedo: 0.442,
      rotationPeriodHours: 16.11,
      orbitalPeriodDays: 60182,
      semiMajorAxisKm: 4495060000,
      eccentricity: 0.009,
      inclinationDeg: 1.769,
      horizonsId: "899",
      naifId: "899",
      systemId: "system-neptune",
      featured: true,
    }),
    makePlanet({
      id: "pluto",
      officialName: "Pluto",
      chineseName: "冥王星",
      englishName: "Pluto",
      radiusKm: 1188.3,
      massKg: 1.303e22,
      density: 1.86,
      gravity: 0.62,
      escapeVelocity: 1.21,
      albedo: 0.52,
      rotationPeriodHours: -153.3,
      orbitalPeriodDays: 90560,
      semiMajorAxisKm: 5906440000,
      eccentricity: 0.2488,
      inclinationDeg: 17.16,
      horizonsId: "999",
      naifId: "999",
      systemId: "system-pluto",
      featured: true,
    }),
    makeMoon({
      id: "moon",
      englishName: "Moon",
      chineseName: "月球",
      officialName: "Moon",
      parentId: "earth",
      systemId: "system-earth",
      discoveryText: "Prehistoric; official IAU name retained as Moon",
      meanRadiusKm: 1737.4,
      massKg: 7.342e22,
      density: 3.34,
      gravity: 1.62,
      escapeVelocity: 2.38,
      albedo: 0.12,
      rotationPeriodHours: 655.7,
      orbitalPeriodDays: 27.3217,
      semiMajorAxisKm: 384400,
      eccentricity: 0.0549,
      inclinationDeg: 5.145,
      featured: true,
      horizonsId: "301",
      naifId: "301",
      aliases: ["Luna"],
      shapeUrls: [SOURCE_URLS.moonModel],
    }),
    makeMoon({
      id: "phobos",
      englishName: "Phobos",
      chineseName: "火卫一",
      parentId: "mars",
      systemId: "system-mars",
      discoveryText: "1877, Asaph Hall",
      meanRadiusKm: 11.267,
      triAxialRadiiKm: [13.5, 11.0, 9.1],
      massKg: 1.0659e16,
      density: 1.86,
      gravity: 0.0057,
      escapeVelocity: 0.011,
      albedo: 0.071,
      rotationPeriodHours: 7.65,
      orbitalPeriodDays: 0.3189,
      semiMajorAxisKm: 9377,
      eccentricity: 0.0151,
      inclinationDeg: 1.093,
      featured: true,
      horizonsId: "401",
      naifId: "401",
      shapeUrls: [SOURCE_URLS.phobosModel],
    }),
    makeMoon({
      id: "deimos",
      englishName: "Deimos",
      chineseName: "火卫二",
      parentId: "mars",
      systemId: "system-mars",
      discoveryText: "1877, Asaph Hall",
      meanRadiusKm: 6.2,
      triAxialRadiiKm: [7.5, 6.1, 5.2],
      massKg: 1.4762e15,
      density: 1.47,
      gravity: 0.003,
      escapeVelocity: 0.0056,
      albedo: 0.068,
      rotationPeriodHours: 30.35,
      orbitalPeriodDays: 1.2624,
      semiMajorAxisKm: 23460,
      eccentricity: 0.0002,
      inclinationDeg: 1.79,
      featured: true,
      horizonsId: "402",
      naifId: "402",
    }),
    makeMoon({
      id: "io",
      englishName: "Io",
      chineseName: "木卫一",
      parentId: "jupiter",
      systemId: "system-jupiter",
      discoveryText: "1610, Galileo Galilei",
      meanRadiusKm: 1821.6,
      massKg: 8.9319e22,
      density: 3.53,
      gravity: 1.796,
      escapeVelocity: 2.56,
      albedo: 0.63,
      rotationPeriodHours: 42.46,
      orbitalPeriodDays: 1.769,
      semiMajorAxisKm: 421700,
      eccentricity: 0.0041,
      inclinationDeg: 0.05,
      featured: true,
      horizonsId: "501",
      naifId: "501",
    }),
    makeMoon({
      id: "europa",
      englishName: "Europa",
      chineseName: "欧罗巴",
      parentId: "jupiter",
      systemId: "system-jupiter",
      discoveryText: "1610, Galileo Galilei",
      meanRadiusKm: 1560.8,
      massKg: 4.7998e22,
      density: 3.01,
      gravity: 1.314,
      escapeVelocity: 2.03,
      albedo: 0.67,
      rotationPeriodHours: 85.23,
      orbitalPeriodDays: 3.551,
      semiMajorAxisKm: 671100,
      eccentricity: 0.009,
      inclinationDeg: 0.47,
      featured: true,
      horizonsId: "502",
      naifId: "502",
      shapeUrls: [SOURCE_URLS.europaModel],
    }),
    makeMoon({
      id: "ganymede",
      englishName: "Ganymede",
      chineseName: "盖尼米得",
      parentId: "jupiter",
      systemId: "system-jupiter",
      discoveryText: "1610, Galileo Galilei",
      meanRadiusKm: 2634.1,
      massKg: 1.4819e23,
      density: 1.94,
      gravity: 1.428,
      escapeVelocity: 2.74,
      albedo: 0.43,
      rotationPeriodHours: 171.7,
      orbitalPeriodDays: 7.155,
      semiMajorAxisKm: 1070400,
      eccentricity: 0.0013,
      inclinationDeg: 0.2,
      featured: true,
      horizonsId: "503",
      naifId: "503",
    }),
    makeMoon({
      id: "callisto",
      englishName: "Callisto",
      chineseName: "卡利斯托",
      parentId: "jupiter",
      systemId: "system-jupiter",
      discoveryText: "1610, Galileo Galilei",
      meanRadiusKm: 2410.3,
      massKg: 1.0759e23,
      density: 1.83,
      gravity: 1.235,
      escapeVelocity: 2.44,
      albedo: 0.17,
      rotationPeriodHours: 400.5,
      orbitalPeriodDays: 16.689,
      semiMajorAxisKm: 1882700,
      eccentricity: 0.007,
      inclinationDeg: 0.192,
      featured: true,
      horizonsId: "504",
      naifId: "504",
    }),
    makeMoon({
      id: "amalthea",
      englishName: "Amalthea",
      chineseName: "阿玛尔忒亚",
      parentId: "jupiter",
      systemId: "system-jupiter",
      discoveryText: "1892, E. E. Barnard",
      meanRadiusKm: 83.5,
      triAxialRadiiKm: [125, 73, 64],
      orbitalPeriodDays: 0.498,
      semiMajorAxisKm: 181400,
      albedo: 0.09,
      rotationPeriodHours: 11.95,
      horizonsId: "505",
      naifId: "505",
    }),
    ...[
      "Himalia",
      "Elara",
      "Pasiphae",
      "Sinope",
      "Lysithea",
      "Carme",
      "Ananke",
      "Leda",
      "Metis",
      "Adrastea",
      "Thebe",
      "Callirrhoe",
      "Themisto",
      "Megaclite",
      "Taygete",
      "Chaldene",
      "Harpalyke",
      "Kalyke",
      "Iocaste",
      "Erinome",
      "Isonoe",
      "Praxidike",
      "Autonoe",
      "Thyone",
      "Hermippe",
      "Aitne",
      "Eurydome",
      "Euanthe",
      "Euporie",
      "Orthosie",
      "Sponde",
      "Kale",
      "Pasithee",
      "Hegemone",
      "Aoede",
      "Thelxinoe",
      "Arche",
      "Kallichore",
      "Helike",
      "Carpo",
      "Eukelade",
      "Cyllene",
      "Kore",
      "Herse",
      "Dia",
      "Eirene",
      "Philophrosyne",
      "Eupheme",
      "Valetudo",
      "Pandia",
      "Ersa",
    ].map((name) =>
      makeMoon({
        id: slugify(name),
        englishName: name,
        chineseName: name,
        parentId: "jupiter",
        systemId: "system-jupiter",
        discoveryText: "See JPL SSD Planetary Satellite Discovery Circumstances",
        featured: false,
        horizonsId: null,
        naifId: null,
      }),
    ),
    makeMoon({
      id: "mimas",
      englishName: "Mimas",
      chineseName: "弥玛斯",
      parentId: "saturn",
      systemId: "system-saturn",
      discoveryText: "1789, William Herschel",
      meanRadiusKm: 198.2,
      massKg: 3.7493e19,
      density: 1.15,
      gravity: 0.064,
      escapeVelocity: 0.159,
      albedo: 0.96,
      rotationPeriodHours: 22.62,
      orbitalPeriodDays: 0.942,
      semiMajorAxisKm: 185539,
      horizonsId: "601",
      naifId: "601",
    }),
    makeMoon({
      id: "enceladus",
      englishName: "Enceladus",
      chineseName: "恩克拉多斯",
      parentId: "saturn",
      systemId: "system-saturn",
      discoveryText: "1789, William Herschel",
      meanRadiusKm: 252.1,
      massKg: 1.08022e20,
      density: 1.61,
      gravity: 0.113,
      escapeVelocity: 0.239,
      albedo: 1.38,
      rotationPeriodHours: 32.89,
      orbitalPeriodDays: 1.37,
      semiMajorAxisKm: 238042,
      featured: true,
      horizonsId: "602",
      naifId: "602",
      shapeUrls: [SOURCE_URLS.enceladusModel],
    }),
    makeMoon({
      id: "tethys",
      englishName: "Tethys",
      chineseName: "特提斯",
      parentId: "saturn",
      systemId: "system-saturn",
      discoveryText: "1684, G. D. Cassini",
      meanRadiusKm: 531.1,
      orbitalPeriodDays: 1.888,
      semiMajorAxisKm: 294672,
      horizonsId: "603",
      naifId: "603",
    }),
    makeMoon({
      id: "dione",
      englishName: "Dione",
      chineseName: "狄俄涅",
      parentId: "saturn",
      systemId: "system-saturn",
      discoveryText: "1684, G. D. Cassini",
      meanRadiusKm: 561.4,
      orbitalPeriodDays: 2.737,
      semiMajorAxisKm: 377415,
      horizonsId: "604",
      naifId: "604",
    }),
    makeMoon({
      id: "rhea",
      englishName: "Rhea",
      chineseName: "瑞亚",
      parentId: "saturn",
      systemId: "system-saturn",
      discoveryText: "1672, G. D. Cassini",
      meanRadiusKm: 763.8,
      orbitalPeriodDays: 4.518,
      semiMajorAxisKm: 527108,
      horizonsId: "605",
      naifId: "605",
    }),
    makeMoon({
      id: "titan",
      englishName: "Titan",
      chineseName: "泰坦",
      parentId: "saturn",
      systemId: "system-saturn",
      discoveryText: "1655, Christiaan Huygens",
      meanRadiusKm: 2574.7,
      massKg: 1.3452e23,
      density: 1.88,
      gravity: 1.352,
      escapeVelocity: 2.64,
      albedo: 0.22,
      rotationPeriodHours: 382.7,
      orbitalPeriodDays: 15.945,
      semiMajorAxisKm: 1221870,
      featured: true,
      horizonsId: "606",
      naifId: "606",
      shapeUrls: [SOURCE_URLS.titanModel],
    }),
    makeMoon({
      id: "hyperion",
      englishName: "Hyperion",
      chineseName: "许珀里翁",
      parentId: "saturn",
      systemId: "system-saturn",
      discoveryText: "1848, Bond and Lassell",
      meanRadiusKm: 135,
      triAxialRadiiKm: [180.1, 133, 102.7],
      orbitalPeriodDays: 21.277,
      semiMajorAxisKm: 1481010,
      horizonsId: "607",
      naifId: "607",
    }),
    makeMoon({
      id: "iapetus",
      englishName: "Iapetus",
      chineseName: "伊阿佩托斯",
      parentId: "saturn",
      systemId: "system-saturn",
      discoveryText: "1671, G. D. Cassini",
      meanRadiusKm: 734.5,
      orbitalPeriodDays: 79.322,
      semiMajorAxisKm: 3560820,
      horizonsId: "608",
      naifId: "608",
    }),
    ...[
      "Phoebe",
      "Janus",
      "Epimetheus",
      "Helene",
      "Telesto",
      "Calypso",
      "Atlas",
      "Prometheus",
      "Pandora",
      "Pan",
      "Ymir",
      "Paaliaq",
      "Tarvos",
      "Ijiraq",
      "Suttungr",
      "Kiviuq",
      "Mundilfari",
      "Albiorix",
      "Skathi",
      "Erriapus",
      "Siarnaq",
      "Tarqeq",
      "Aegaeon",
      "Methone",
      "Anthe",
      "Pallene",
      "Polydeuces",
      "Daphnis",
      "Aegir",
      "Bebhionn",
      "Bergelmir",
      "Bestla",
      "Farbauti",
      "Fenrir",
      "Fornjot",
      "Hati",
      "Hyrrokkin",
      "Kari",
      "Loge",
      "Skoll",
      "Surtur",
      "Jarnsaxa",
      "Greip",
      "Gridr",
      "Angrboda",
      "Skrymir",
      "Gerd",
      "Eggther",
      "Beli",
      "Gunnlod",
      "Thiazzi",
    ].map((name) =>
      makeMoon({
        id: slugify(name),
        englishName: name,
        chineseName: name,
        parentId: "saturn",
        systemId: "system-saturn",
        discoveryText: "See JPL SSD Planetary Satellite Discovery Circumstances",
      }),
    ),
    makeMoon({
      id: "miranda",
      englishName: "Miranda",
      chineseName: "米兰达",
      parentId: "uranus",
      systemId: "system-uranus",
      discoveryText: "1948, Gerard Kuiper",
      meanRadiusKm: 235.8,
      orbitalPeriodDays: 1.413,
      semiMajorAxisKm: 129900,
      horizonsId: "705",
      naifId: "705",
    }),
    ...([
      ["Ariel", "艾瑞尔"],
      ["Umbriel", "翁布里厄尔"],
      ["Titania", "泰坦妮娅"],
      ["Oberon", "奥伯龙"],
      ["Cordelia", "科迪莉娅"],
      ["Ophelia", "奥菲莉娅"],
      ["Bianca", "比安卡"],
      ["Cressida", "克瑞西达"],
      ["Desdemona", "苔丝狄蒙娜"],
      ["Juliet", "朱丽叶"],
      ["Portia", "鲍西娅"],
      ["Rosalind", "罗莎琳德"],
      ["Belinda", "贝琳达"],
      ["Puck", "帕克"],
      ["Caliban", "卡利班"],
      ["Sycorax", "西克拉克斯"],
      ["Prospero", "普洛斯彼罗"],
      ["Setebos", "塞特波斯"],
      ["Stephano", "斯特凡诺"],
      ["Trinculo", "特林库洛"],
      ["Francisco", "弗朗西斯科"],
      ["Margaret", "玛格丽特"],
      ["Ferdinand", "斐迪南"],
      ["Perdita", "佩狄塔"],
      ["Mab", "玛布"],
      ["Cupid", "丘比特"],
    ] as const).map(([name, chineseName]) =>
      makeMoon({
        id: slugify(name),
        englishName: name,
        chineseName,
        parentId: "uranus",
        systemId: "system-uranus",
        discoveryText: "See JPL SSD Planetary Satellite Discovery Circumstances",
      }),
    ),
    makeMoon({
      id: "triton",
      englishName: "Triton",
      chineseName: "海卫一",
      parentId: "neptune",
      systemId: "system-neptune",
      discoveryText: "1846, William Lassell",
      meanRadiusKm: 1353.4,
      massKg: 2.14e22,
      density: 2.06,
      gravity: 0.779,
      escapeVelocity: 1.455,
      albedo: 0.76,
      rotationPeriodHours: -141.04,
      orbitalPeriodDays: -5.877,
      semiMajorAxisKm: 354759,
      featured: true,
      horizonsId: "801",
      naifId: "801",
    }),
    ...([
      ["Nereid", "海卫二"],
      ["Naiad", "海卫三"],
      ["Thalassa", "海卫四"],
      ["Despina", "海卫五"],
      ["Galatea", "海卫六"],
      ["Larissa", "海卫七"],
      ["Proteus", "海卫八"],
      ["Halimede", "Halimede"],
      ["Sao", "Sao"],
      ["Laomedeia", "Laomedeia"],
      ["Psamathe", "Psamathe"],
      ["Neso", "Neso"],
      ["Hippocamp", "Hippocamp"],
    ] as const).map(([name, chineseName]) =>
      makeMoon({
        id: slugify(name),
        englishName: name,
        chineseName,
        parentId: "neptune",
        systemId: "system-neptune",
        discoveryText: "See JPL SSD Planetary Satellite Discovery Circumstances",
      }),
    ),
    makeMoon({
      id: "charon",
      englishName: "Charon",
      chineseName: "冥卫一",
      parentId: "pluto",
      systemId: "system-pluto",
      discoveryText: "1978, James Christy",
      meanRadiusKm: 606,
      massKg: 1.586e21,
      density: 1.7,
      gravity: 0.288,
      escapeVelocity: 0.59,
      albedo: 0.38,
      rotationPeriodHours: 153.3,
      orbitalPeriodDays: 6.387,
      semiMajorAxisKm: 19571,
      featured: true,
      horizonsId: "901",
      naifId: "901",
      shapeUrls: [SOURCE_URLS.charonModel],
    }),
    ...([
      ["Nix", "冥卫二"],
      ["Hydra", "冥卫三"],
      ["Kerberos", "冥卫四"],
      ["Styx", "冥卫五"],
    ] as const).map(([name, chineseName]) =>
      makeMoon({
        id: slugify(name),
        englishName: name,
        chineseName,
        parentId: "pluto",
        systemId: "system-pluto",
        discoveryText: "See JPL SSD Planetary Satellite Discovery Circumstances",
      }),
    ),
  ];

  return bodies.sort((a, b) => a.englishName.localeCompare(b.englishName));
}

export function buildSeedSystems(bodies: Body[]): PlanetSystem[] {
  const definitions = [
    {
      id: "system-earth",
      slug: "earth",
      name: "Earth System",
      chineseName: "地月系统",
      primaryBodyId: "earth",
      featuredBodyIds: ["earth", "moon"],
      description: {
        oneLine: "地球与月球构成观测与比较行星学最重要的近邻系统。",
        short: "地月系统以潮汐作用、双体角动量交换与人类直接探测史为核心价值。",
      },
    },
    {
      id: "system-mars",
      slug: "mars",
      name: "Mars System",
      chineseName: "火星系统",
      primaryBodyId: "mars",
      featuredBodyIds: ["mars", "phobos", "deimos"],
      description: {
        oneLine: "火星系统由主星与两颗微小卫星组成，尺寸反差极强。",
        short: "火卫一和火卫二适合讲解捕获起源、潮汐演化与近行星卫星动力学。",
      },
    },
    {
      id: "system-jupiter",
      slug: "jupiter",
      name: "Jupiter System",
      chineseName: "木星系统",
      primaryBodyId: "jupiter",
      featuredBodyIds: ["jupiter", "io", "europa", "ganymede", "callisto"],
      description: {
        oneLine: "木星系统是研究共振、火山活动与冰卫星海洋的核心舞台。",
        short: "从伽利略卫星到不规则卫星群，木星系统层次丰富且教学价值极高。",
      },
    },
    {
      id: "system-saturn",
      slug: "saturn",
      name: "Saturn System",
      chineseName: "土星系统",
      primaryBodyId: "saturn",
      featuredBodyIds: ["saturn", "titan", "enceladus", "mimas", "iapetus"],
      description: {
        oneLine: "土星系统把行星环、冰卫星与远距不规则卫星组合成最复杂的层级之一。",
        short: "MVP 会重点突出泰坦与恩克拉多斯，同时保留长尾卫星目录与轨道入口。",
      },
    },
    {
      id: "system-uranus",
      slug: "uranus",
      name: "Uranus System",
      chineseName: "天王星系统",
      primaryBodyId: "uranus",
      featuredBodyIds: ["uranus", "titania", "oberon", "ariel", "umbriel"],
      description: {
        oneLine: "天王星系统适合观察倾斜自转轴与多层卫星家族的组合效应。",
        short: "主星极端倾角和莎士比亚主题命名共同构成了独特的系统辨识度。",
      },
    },
    {
      id: "system-neptune",
      slug: "neptune",
      name: "Neptune System",
      chineseName: "海王星系统",
      primaryBodyId: "neptune",
      featuredBodyIds: ["neptune", "triton", "nereid", "proteus"],
      description: {
        oneLine: "海王星系统围绕逆行巨卫星海卫一展开，是捕获起源研究的关键案例。",
        short: "海王星系统成员不多，但动力学和起源问题都非常鲜明。",
      },
    },
    {
      id: "system-pluto",
      slug: "pluto",
      name: "Pluto System",
      chineseName: "冥王星系统",
      primaryBodyId: "pluto",
      featuredBodyIds: ["pluto", "charon", "nix", "hydra"],
      description: {
        oneLine: "冥王星系统是理解矮行星系统与双体重心的最佳入口。",
        short: "冥王星与冥卫一质量比很高，其余小卫星则展示了紧凑系统的层级结构。",
      },
    },
  ];

  return definitions.map((definition) => {
    const memberIds = bodies
      .filter((body) => body.systemId === definition.id || body.id === definition.primaryBodyId)
      .map((body) => body.id)
      .sort();

    const members = bodies.filter((body) => memberIds.includes(body.id));

    return {
      ...definition,
      memberIds,
      stats: {
        totalBodies: memberIds.length,
        naturalSatellites: members.filter((body) => body.bodyType === "natural_satellite").length,
        withHighFidelityShape: members.filter((body) => body.hasHighFidelityShape).length,
      },
      orbitCoverage: {
        sampledBodyIds: [],
        referenceOnlyBodyIds: memberIds.filter((id) => id !== definition.primaryBodyId),
      },
    };
  });
}
